compatibility_date = "2024-05-26"
compatibility_flags = [ "nodejs_compat" ]
account_id = "mohammed"
main = "src/worker.ts"

# #########################
#         Dev Env        #
# ########################
name = "remission_supervisor_service_dev"

[vars]
ENVIRONMENT = "dev"

[[kv_namespaces]]
binding = "SUPERVISOR_KV"
id = "111"

[[r2_buckets]]
binding = 'SUPERVISOR_BUCKET'
bucket_name = '111'

[dev]
port = 4242

# #########################
#     Staging Env        #
# ########################

[env.staging]
name = "remission_supervisor_service_staging"
workers_dev = false

[env.staging.vars]
ENVIRONMENT = "staging"

[[env.staging.kv_namespaces]]
binding = "SUPERVISOR_KV"
id = "__STAGING_KV_ID__"

[[env.staging.r2_buckets]]
binding = 'SUPERVISOR_BUCKET'
bucket_name = '__STAGING_BUCKET_NAME__'

# ########################
#     Production Env     #
# ########################

[env.production]
name = "remission_supervisor_service_production"
workers_dev = false

[env.production.vars]
ENVIRONMENT = "production"

[[env.production.kv_namespaces]]
binding = "SUPERVISOR_KV"
id = "__PRODUCTION_KV_ID__"

[[env.production.r2_buckets]]
binding = 'SUPERVISOR_BUCKET'
bucket_name = '__PRODUCTION_BUCKET_NAME__'