name: Deploy to production

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Generate wrangler.toml
        run: npm run generate-config staging

      - name: Publish app
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          preCommands: |
            npm install
          command: deploy --env production
          environment: production
          secrets: |
            CF_ACCOUNT_ID
            PRODUCTION_SCRIPT_NAME
            PRODUCTION_KV_ID
            PRODUCTION_BUCKET_NAME
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          PRODUCTION_SCRIPT_NAME: ${{ secrets.PRODUCTION_SCRIPT_NAME }}
          PRODUCTION_KV_ID: ${{ secrets.PRODUCTION_KV_ID }}
          PRODUCTION_BUCKET_NAME: ${{ secrets.PRODUCTION_BUCKET_NAME }}
